name: Exercice 2
on: push
jobs:
  Exercie2:
    runs-on: ubuntu-latest
    steps:
      - name: install nodeJs
        uses: actions/checkout@v3
      - name: install npm
        run: npm install
      - name: run lint
        run: npm run lint
      - name: run build
        run: npm run build

