name: Exercice 2
on: push
jobs:
  Exercie2:
    runs-on: ubuntu-latest
    steps:
      - name: "install nodeJs"
        uses: actions/checkout@v3
  Exercie3:
    needs: Exercie2
    runs-on: ubuntu-latest
    steps:
      - name: install npm
        run: npm ci
  Exercie4:
    needs: Exercie3
    runs-on: ubuntu-latest
    steps:
      - name: run lint
        run: npm lint

